// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateInfrastructure():Promise<string>;

export function DestroyInfrastructure():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function IsInfrastructureDeployed():Promise<boolean>;
