// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateInfrastructure() {
  return window['go']['main']['App']['CreateInfrastructure']();
}

export function DestroyInfrastructure() {
  return window['go']['main']['App']['DestroyInfrastructure']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
